<?php
global $_W;
$sql = "
DROP TABLE IF EXISTS ims_ewei_shop_adv;
DROP TABLE IF EXISTS `ims_ewei_shop_article` ;
DROP TABLE IF EXISTS `ims_ewei_shop_article_category` ;
DROP TABLE IF EXISTS `ims_ewei_shop_article_category_copy` ;
DROP TABLE IF EXISTS `ims_ewei_shop_article_sys` ;
DROP TABLE IF EXISTS `ims_ewei_shop_article_share` ;
DROP TABLE IF EXISTS `ims_ewei_shop_article_report` ;
DROP TABLE IF EXISTS `ims_ewei_shop_article_log` ;
DROP TABLE IF EXISTS `ims_ewei_shop_article_category` ;
DROP TABLE IF EXISTS ims_ewei_shop_carrier;
DROP TABLE IF EXISTS ims_ewei_shop_category;
DROP TABLE IF EXISTS ims_ewei_shop_commission_apply;
DROP TABLE IF EXISTS ims_ewei_shop_commission_clickcount;
DROP TABLE IF EXISTS ims_ewei_shop_commission_level;
DROP TABLE IF EXISTS ims_ewei_shop_commission_log;
DROP TABLE IF EXISTS ims_ewei_shop_commission_shop;
DROP TABLE IF EXISTS ims_ewei_shop_coupon;
DROP TABLE IF EXISTS ims_ewei_shop_coupon_category;
DROP TABLE IF EXISTS ims_ewei_shop_coupon_data;
DROP TABLE IF EXISTS ims_ewei_shop_coupon_guess;
DROP TABLE IF EXISTS ims_ewei_shop_coupon_log;
DROP TABLE IF EXISTS ims_ewei_shop_creditshop_adv;
DROP TABLE IF EXISTS ims_ewei_shop_creditshop_category;
DROP TABLE IF EXISTS ims_ewei_shop_creditshop_goods;
DROP TABLE IF EXISTS ims_ewei_shop_creditshop_log;
DROP TABLE IF EXISTS ims_ewei_shop_designer;
DROP TABLE IF EXISTS ims_ewei_shop_designer_menu;
DROP TABLE IF EXISTS ims_ewei_shop_dispatch;
DROP TABLE IF EXISTS ims_ewei_shop_exhelper_express;
DROP TABLE IF EXISTS ims_ewei_shop_exhelper_senduser;
DROP TABLE IF EXISTS ims_ewei_shop_exhelper_sys;
DROP TABLE IF EXISTS ims_ewei_shop_express;
DROP TABLE IF EXISTS ims_ewei_shop_feedback;
DROP TABLE IF EXISTS ims_ewei_shop_goods;
DROP TABLE IF EXISTS ims_ewei_shop_goods_comment;
DROP TABLE IF EXISTS ims_ewei_shop_goods_option;
DROP TABLE IF EXISTS ims_ewei_shop_goods_param;
DROP TABLE IF EXISTS ims_ewei_shop_goods_spec;
DROP TABLE IF EXISTS ims_ewei_shop_goods_spec_item;
DROP TABLE IF EXISTS ims_ewei_shop_member;
DROP TABLE IF EXISTS ims_ewei_shop_member_address;
DROP TABLE IF EXISTS ims_ewei_shop_member_cart;
DROP TABLE IF EXISTS ims_ewei_shop_member_favorite;
DROP TABLE IF EXISTS ims_ewei_shop_member_group;
DROP TABLE IF EXISTS ims_ewei_shop_member_history;
DROP TABLE IF EXISTS ims_ewei_shop_member_level;
DROP TABLE IF EXISTS ims_ewei_shop_member_log;
DROP TABLE IF EXISTS ims_ewei_shop_member_message_template;
DROP TABLE IF EXISTS ims_ewei_shop_notice;
DROP TABLE IF EXISTS ims_ewei_shop_order;
DROP TABLE IF EXISTS ims_ewei_shop_order_comment;
DROP TABLE IF EXISTS ims_ewei_shop_order_goods;
DROP TABLE IF EXISTS ims_ewei_shop_order_refund;
DROP TABLE IF EXISTS ims_ewei_shop_perm_log;
DROP TABLE IF EXISTS ims_ewei_shop_perm_plugin;
DROP TABLE IF EXISTS ims_ewei_shop_perm_role;
DROP TABLE IF EXISTS ims_ewei_shop_perm_user;
DROP TABLE IF EXISTS ims_ewei_shop_plugin;
DROP TABLE IF EXISTS ims_ewei_shop_poster;
DROP TABLE IF EXISTS ims_ewei_shop_poster_log;
DROP TABLE IF EXISTS ims_ewei_shop_poster_qr;
DROP TABLE IF EXISTS ims_ewei_shop_poster_scan;
DROP TABLE IF EXISTS ims_ewei_shop_postera;
DROP TABLE IF EXISTS ims_ewei_shop_postera_log;
DROP TABLE IF EXISTS ims_ewei_shop_postera_qr;
DROP TABLE IF EXISTS ims_ewei_shop_saler;
DROP TABLE IF EXISTS ims_ewei_shop_store;
DROP TABLE IF EXISTS ims_ewei_shop_sysset;
DROP TABLE IF EXISTS ims_ewei_shop_system_copyright;
DROP TABLE IF EXISTS ims_ewei_shop_virtual_category;
DROP TABLE IF EXISTS ims_ewei_shop_virtual_data;
DROP TABLE IF EXISTS ims_ewei_shop_virtual_type;
DROP TABLE IF EXISTS `ims_ewei_shop_diyform_type`;
";
pdo_query($sql);